# Site settings
title: My Jekyll Site
description: A simple description of my Jekyll site.

# Build settings
markdown: kramdown

# Exclude files and directories from the build
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - .gitignore
  - .github
  - .DS_Store
  - store
  - .jekyll-cache

# Permalinks configuration
permalink: pretty